micronaut:
  application:
    name: propostaRestWrapper

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10

  channels:
    proposal:
      address: ${PROPOSAL_ADDRESS:`localhost:50051`}
      plaintext: true
      max-retry-attempts: 10

jackson:
  serialization:
    writeDateAsTimestampos: false
